apiVersion: v1
kind: Service
metadata:
  name: ms-ventas-report-service
  labels:
    app: ms-ventas-report
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: ms-ventas-report