apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedidos-deployment
  labels:
    app: pedidos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pedidos
  template:
    metadata:
      labels:
        app: pedidos
    spec:
      containers:
      - name: pedidos
        image: gcr.io/misw-4301-native-cloud-433702/github.com/xcode-miso/pedidos
        ports:
        - containerPort: 3001
        env:
        - name: FLASK_DEBUG
          value: "1" #
        - name: DATABASE_USER
          value: "%DATABASE_USER%"
        - name: DATABASE_PASSWORD
          value: "%DATABASE_PASSWORD%"
        - name: DATABASE_PORT
          value: "%DATABASE_PORT%"
        - name: DATABASE_URL
          value: "%DATABASE_URL%"
        - name: DATABASE_NAME
          value: "%DATABASE_NAME%"
        - name: GOOGLE_CLOUD_PROJECT
          value: "%GOOGLE_CLOUD_PROJECT%"
        - name: SQLALCHEMY_DATABASE_URI
          value: "%SQLALCHEMY_DATABASE_URI%"
        - name: DB_TYPE
          value: "%DB_TYPE%"