apiVersion: v1
kind: Service
metadata:
  name: pedidos
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: pedidos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
