steps:
  - name: 'bash'
    script: |
      echo $GMAPS_API_KEY
      sed -i 's/%GMAPS_API_KEY%/${_GMAPS_API_KEY}/g' ./front/aplicacion-web/src/index.html
      cat ./front/aplicacion-web/src/index.html
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
        'run', 
        'deploy',
        'aplicacion-web',
        '--allow-unauthenticated',
        '--region',
        'us-central1',
        '--source',
        'front/aplicacion-web',
      ]
options:
  logging: CLOUD_LOGGING_ONLY