steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
        'run', 
        'deploy', 
        'aplicacion-web', 
        '--image', 
        'gcr.io/misw-4301-native-cloud-433702/aplicacion-web', 
        '--platform', 
        'managed', 
        '--allow-unauthenticated'
      ]
options:
  logging: CLOUD_LOGGING_ONLY