steps:
 - name: 'node'
   entrypoint: 'npm'
   args: ['ci', '--prefix', 'front/aplicacion-web']
 - name: 'node'
   entrypoint: 'npm'
   args: ['run', 'build', '--prefix', 'front/aplicacion-web']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
        'run', 
        'deploy',
        'aplicacion-web',
        '--allow-unauthenticated',
        '--region',
        'us-central1',
        '--source',
        'front/aplicacion-web',
      ]
options:
  logging: CLOUD_LOGGING_ONLY 