steps:
  - name: 'node'
    entrypoint: 'npm'
    dir: 'front/aplicacion-web'
    args: [
      'run',
      'build:env'
    ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
        'run', 
        'deploy',
        'aplicacion-web',
        '--allow-unauthenticated',
        '--region',
        'us-central1',
        '--source',
        'front/aplicacion-web',
      ]
options:
  logging: CLOUD_LOGGING_ONLY