steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/aplicacion-web', '.']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
        'run', 
        'deploy', 
        'aplicacion-web', 
        '--image', 
        'gcr.io/$PROJECT_ID/aplicacion-web', 
        '--platform', 
        'managed',
        '--allow-unauthenticated'
      ]