steps:
  - name: Create Firebase keys files
    run: |
      echo __FIREBASE_ADMIN_KEYS | base64 -d > ./front/aplicacion-web/keys.json
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - '-c' 
      - sed -i 's/%GMAPS_API_KEY%/'${_GMAPS_API_KEY}'/g' ./front/aplicacion-web/src/index.html
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - '-c' 
      - cat ./front/aplicacion-web/src/index.html
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
        'run', 
        'deploy',
        'aplicacion-web',
        '--allow-unauthenticated',
        '--region',
        'us-central1',
        '--source',
        'front/aplicacion-web',
      ]
options:
  logging: CLOUD_LOGGING_ONLY
  automapSubstitutions: true