steps:
  - name: 'bash'
    script: |
      sed -i "s/__GMAPS_API_KEY__/$GMAPS_API_KEY/g" ./front/aplicacion-web/src/index.html
      cat ./front/aplicacion-web/src/index.html
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
        'run', 
        'deploy',
        'aplicacion-web',
        '--allow-unauthenticated',
        '--region',
        'us-central1',
        '--source',
        'front/aplicacion-web',
      ]
options:
  logging: CLOUD_LOGGING_ONLY