steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
        'run', 
        'deploy', 
        'aplicacion-web',
        '--platform', 
        'managed', 
        '--allow-unauthenticated',
        '--region',
        'us-central1'
      ]
options:
  logging: CLOUD_LOGGING_ONLY