swagger: "2.0"
info:
  title: "API de Microservicios"
  version: "1.0.0"
host: "microservicios-gateway-1qkjvfz9.uc.gateway.dev"
schemes:
  - "https"
security:
  - firebase: []
paths:
  /api/compras/detalle:
    post:
      operationId: "createDetalleCompra"
      summary: "Crear detalle de compra"
      description: "Crea un detalle de compra en el sistema de compras."
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Datos del detalle de compra"
          required: true
          schema:
            type: "object"
            properties:
              nombre:
                type: "string"
              fabricante_id:
                type: "integer"
              cantidad:
                type: "integer"
              precio:
                type: "number"
      responses:
        201:
          description: "Detalle de compra creado"
      x-google-backend:
        address: "http://compras.cppxcode.shop/api/compras/detalle"

  /api/fabricantes:
    get:
      operationId: "listFabricantes"
      summary: "Listar fabricantes"
      description: "Devuelve una lista de fabricantes en el sistema de compras."
      produces:
        - "application/json"
      responses:
        200:
          description: "Lista de fabricantes"
      x-google-backend:
        address: "http://compras.cppxcode.shop/api/fabricantes"

  /api/inventarios/productos:
    get:
      operationId: "listInventarioProductos"
      summary: "Listar productos en inventario"
      description: "Devuelve la lista de productos registrados en inventario."
      produces:
        - "application/json"
      responses:
        200:
          description: "Lista de productos en inventario"
      x-google-backend:
        address: "http://inventarios.cppxcode.shop/api/inventarios/productos"

securityDefinitions:
  firebase:
    type: "oauth2"
    flow: "implicit"
    authorizationUrl: ""
    x-google-issuer: "https://securetoken.google.com/misw-4301-native-cloud-433702"
    x-google-jwks_uri: "https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com"
    x-google-audiences: "misw-4301-native-cloud-433702"