steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud api-gateway api-configs create $TAG_NAME --api=microservicios-api --openapi-spec=api-spec-v2.yaml  --project=$PROJECT_ID --backend-auth-service-account=$PROJECT_ID@appspot.gserviceaccount.com
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud api-gateway gateways update microservicios-gateway  --api=microservicios-api  --api-config=microservicios-config-v34 --location=us-central1  --project=$PROJECT_ID