version: "3.9"
services:
  pubsub:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    command: >
      gcloud beta emulators pubsub start --host-port=0.0.0.0:8681
    ports:
      - "8681:8681"

  ms_compras:
    build: ../ms_compras         
    environment:
      PUBSUB_EMULATOR_HOST: pubsub:8681
      GCP_PROJECT: test-proj
    depends_on: [pubsub]
    ports: ["5001:5001"]

  pedidos:
    build: ../pedidos
    environment:
      PUBSUB_EMULATOR_HOST: pubsub:8681
      GCP_PROJECT: test-proj
    depends_on: [pubsub]
    ports: ["5003:5003"]

  ms_inventarios:
    build: ../ms_inventarios
    environment:
      PUBSUB_EMULATOR_HOST: pubsub:8681
      GCP_PROJECT: test-proj
    depends_on: [pubsub]
    ports: ["5002:5002"]