steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
    - 'build'
    - '-t'
    - 'gcr.io/misw-4301-native-cloud-433702/github.com/xcode-miso/pedidos:latest'
    - '-f'
    - 'services/pedidos/Dockerfile'
    - 'services/pedidos'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/misw-4301-native-cloud-433702/github.com/xcode-miso/pedidos:latest']
  # REPLACE GOOGLE PROJECT
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
    - '-c'
    - sed -i 's/%GOOGLE_CLOUD_PROJECT%/'${_GOOGLE_CLOUD_PROJECT}'/g' services/pedidos/gcp/kubernetes/deployment.yaml
  # REPLACE DATABASE_URL
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
    - '-c'
    - sed -i 's/%DATABASE_URL%/'${_DATABASE_URL}'/g' services/pedidos/gcp/kubernetes/deployment.yaml
  # REPLACE DATABASE_NAME
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
    - '-c'
    - sed -i 's/%DATABASE_NAME%/'${_DATABASE_NAME}'/g' services/pedidos/gcp/kubernetes/deployment.yaml
  # REPLACE DATABASE_USER
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
    - '-c'
    - sed -i 's/%DATABASE_USER%/'${_DATABASE_USER}'/g' services/pedidos/gcp/kubernetes/deployment.yaml
  # REPLACE DATABASE_PASSWORD
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
    - '-c'
    - sed -i 's/%DATABASE_PASSWORD%/'${_DATABASE_PASSWORD}'/g' services/pedidos/gcp/kubernetes/deployment.yaml
  # REPLACE DATABASE_PORT
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
    - '-c'
    - sed -i 's/%DATABASE_PORT%/'${_DATABASE_PORT}'/g' services/pedidos/gcp/kubernetes/deployment.yaml
   # REPLACE SQLALCHEMY_DATABASE_URI
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
    - '-c'
    - sed -i 's/%SQLALCHEMY_DATABASE_URI%/'${_SQLALCHEMY_DATABASE_URI}'/g' services/pedidos/gcp/kubernetes/deployment.yaml
   # REPLACE DB_TYPE
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
    - '-c'
    - sed -i 's/%DB_TYPE%/'${_DB_TYPE}'/g' services/pedidos/gcp/kubernetes/deployment.yaml
  # Kubernetes Deploy
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=services/pedidos/gcp/kubernetes/deployment.yaml
    - --location=us-central1
    - --cluster=my-cluster
    - --image=gcr.io/misw-4301-native-cloud-433702/github.com/xcode-miso/pedidos:latest
  # Kubernetes Service Updated
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=services/pedidos/gcp/kubernetes/service.yaml
    - --location=us-central1
    - --cluster=my-cluster
    - --output=output/service
options:
  logging: CLOUD_LOGGING_ONLY