apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-inventarios-deployment
  labels:
    app: ms-inventarios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-inventarios
  template:
    metadata:
      labels:
        app: ms-inventarios
    spec:
      containers:
      - name: ms-inventarios
        image: gcr.io/misw-4301-native-cloud-433702/ms_inventarios:latest
        ports:
        - containerPort: 5002
        env:
        - name: DB_HOST
          value: "%DATABASE_URL%"
        - name: DB_PORT
          value: "%DATABASE_PORT%"
        - name: DB_USER
          value: "%DATABASE_USER%"
        - name: DB_PASS
          value: "%DATABASE_PASSWORD%"
        - name: DB_NAME
          value: "%DATABASE_NAME%"
        - name: GCP_PROJECT_ID
          value: "misw-4301-native-cloud-433702"
        - name: PUBSUB_SUBSCRIPTION_ID
          value: "inventarios-sub"