apiVersion: apps/v1
kind: Deployment
metadata:
  name: recomendations-query-deployment
  labels:
    app: recomendations-query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recomendations-query
  template:
    metadata:
      labels:
        app: recomendations-query
    spec:
      containers:
      - name: recomendations-query
        image: gcr.io/misw-4301-native-cloud-433702/recomendations-query:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_URI
          value: "postgresql://admin_read:PASSWORD_123@35.202.68.237:5432/recomendaciones_query_db"
        - name: GCP_PROJECT
          value: "misw-4301-native-cloud-433702"
        - name: PULL_SUBSCRIPTION
          value: "recommendations-pull-sub"