apiVersion: apps/v1
kind: Deployment
metadata:
  name: recomendations-command-deployment
  labels:
    app: recomendations-command
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recomendations-command
  template:
    metadata:
      labels:
        app: recomendations-command
    spec:
      containers:
      - name: recomendations-command
        image: gcr.io/misw-4301-native-cloud-433702/recomendations-command:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_URI
          value: "postgresql://admin_write:PASSWORD_123@34.171.48.199:5432/recomendaciones_command_db"
        - name: VIDEO_BUCKET
          value: "videos_tiendas"
        - name: GCP_PROJECT
          value: "misw-4301-native-cloud-433702"
        - name: PUBSUB_TOPIC
          value: "video-procesado-topic"