apiVersion: v1
kind: Service
metadata:
  name: recomendations-command-service
spec:
  type: LoadBalancer
  selector:
    app: recomendations-command
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
