steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
    - '-c'
    - 'echo "{\"version\": \"$TAG_NAME\"}" > ./services/logistica/version.json'
  - name: 'gcr.io/cloud-builders/docker'
    args:
    - 'build'
    - '-t'
    - 'gcr.io/misw-4301-native-cloud-433702/github.com/xcode-miso/logistica:latest'
    - '-f'
    - 'services/logistica/Dockerfile'
    - 'services/logistica'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/misw-4301-native-cloud-433702/github.com/xcode-miso/logistica:latest']
  # REPLACE GOOGLE MAPS API KEY
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
    - '-c'
    - sed -i 's/%GMAPS_API_KEY%/'${_GMAPS_API_KEY}'/g' services/logistica/gcp/kubernetes/deployment.yaml
  # REPLACE GOOGLE PROJECT
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
    - '-c'
    - sed -i 's/%GOOGLE_CLOUD_PROJECT%/'${_GOOGLE_CLOUD_PROJECT}'/g' services/logistica/gcp/kubernetes/deployment.yaml
  # REPLACE DATABASE_URL
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
    - '-c'
    - sed -i 's/%DATABASE_URL%/'${_DATABASE_URL}'/g' services/logistica/gcp/kubernetes/deployment.yaml
  # REPLACE DATABASE_USER
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
    - '-c'
    - sed -i 's/%DATABASE_USER%/'${_DATABASE_USER}'/g' services/logistica/gcp/kubernetes/deployment.yaml
  # REPLACE DATABASE_PASSWORD
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
    - '-c'
    - sed -i 's/%DATABASE_PASSWORD%/'${_DATABASE_PASSWORD}'/g' services/logistica/gcp/kubernetes/deployment.yaml
  # REPLACE DATABASE_PORT
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
    - '-c'
    - sed -i 's/%DATABASE_PORT%/'${_DATABASE_PORT}'/g' services/logistica/gcp/kubernetes/deployment.yaml
  # Kubernetes Deploy
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=services/logistica/gcp/kubernetes/deployment.yaml
    - --location=us-central1
    - --cluster=my-cluster
    - --image=gcr.io/misw-4301-native-cloud-433702/github.com/xcode-miso/logistica:latest
  # Kubernetes Service Updated
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=services/logistica/gcp/kubernetes/service.yaml
    - --location=us-central1
    - --cluster=my-cluster
    - --output=output/service
options:
  logging: CLOUD_LOGGING_ONLY