version: '3'

services:
  ms_ventas_report:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql+pg8000://admin_read:PASSWORD_123@35.202.68.237:5432/reportes_db
      - ENABLE_PUBSUB=true
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    volumes:
      - .:/app

