apiVersion: v1
kind: Service
metadata:
  name: ms-inventarios-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: ms-inventarios
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5002
  type: ClusterIP