version: "3.8"

services:
  recomendations-command:
    build: ./recomendations_command
    container_name: experiment-command
    ports:
      - "8081:8080"
    environment:
      - WRITE_DB_URI=postgresql://user:password@db_write/recomendaciones_command_db
    depends_on:
      - db_write

  recomendations-query:
    build: ./recomendations_query
    container_name: experiment-query
    ports:
      - "8082:8080"
    environment:
      - READ_DB_URI=postgresql://user:password@db_read/recomendaciones_query_db
    depends_on:
      - db_read

  db_write:
    image: postgres:13
    container_name: experiment-db-write
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: recomendaciones_command_db
    volumes:
      - db_write_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  db_read:
    image: postgres:13
    container_name: experiment-db-read
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: recomendaciones_query_db
    volumes:
      - db_read_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  db_write_data:
  db_read_data:
