apiVersion: apps/v1
kind: Deployment
metadata:
  name: ventas-deployment
  labels:
    app: ventas
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ventas
  template:
    metadata:
      labels:
        app: ventas
    spec:
      containers:
      - name: ventas
        image: gcr.io/misw-4301-native-cloud-433702/ventas:latest
        ports:
        - containerPort: 8080
        env:
        - name : DB_USER
          value: user_ventas_user
        - name: DB_PASSWORD
          value: user_ventas_pass
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: ventas_db
        - name: DB_HOST
          value: "161.132..40.204"