name: Aggregate Coverage Chart

# Se dispara cuando hayan completado los workflows unitarios de *todos* los micros
on:
  workflow_run:
    workflows:
      - "Unit Tests – ms_compras"
      - "Unit Tests – ms_inventarios"
      # añade aquí el nombre de cada uno
    types:
      - completed

jobs:
  aggregate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1) Descarga los artifacts de cobertura de cada micro
      - name: Download ms_compras coverage.xml
        uses: actions/download-artifact@v4
        with:
          name: cov-ms_compras
          path: cov_reports

      - name: Download ms_inventarios coverage.xml
        uses: actions/download-artifact@v4
        with:
          name: cov-ms_inventarios
          path: cov_reports

      # 2) Instala herramientas de coverage y matplotlib
      - name: Setup Python tools
        run: |
          python -m pip install --upgrade pip
          pip install coverage matplotlib

      # 3) Combina los XML y genera un XML unificado
      - name: Combine and emit merged coverage.xml
        run: |
          # coverage combine espera archivos .coverage, pero podemos reusar el xml directamente:
          coverage xml -i -o merged_coverage.xml \
            --include="services/ms_compras/*,services/ms_inventarios/*" \
            cov_reports/coverage-ms_compras.xml \
            cov_reports/coverage-ms_inventarios.xml

      # 4) Genera el gráfico (usa tu script)
      - name: Generate coverage chart
        run: |
          python scripts/generate_coverage_chart.py \
            merged_coverage.xml \
            coverage_chart.png

      # 5) Publica el gráfico como comentario en el PR
      - name: Comment coverage chart on PR
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.workflow_run.pull_requests[0].number }}
          body: |
            ## 📊 Aggregate Coverage
            ![Aggregate Coverage](./coverage_chart.png)

      # 6) (Opcional) Guarda el chart como artifact
      - name: Upload chart artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-chart
          path: coverage_chart.png