name: Coverage Aggregate

on:
  workflow_run:
    # Aquí van los "name:" exactos de tus workflows unitarios
    workflows: [unit-ms_compras, unit-ms_inventarios]

    types:
      - completed

jobs:
  aggregate:
    # Solo corre si ambos terminaron correctamente
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download ms_compras coverage.xml
        uses: actions/download-artifact@v4
        with:
          name: cov-ms_compras
          path: cov_reports

      - name: Download ms_inventarios coverage.xml
        uses: actions/download-artifact@v4
        with:
          name: cov-ms_inventarios
          path: cov_reports

      - name: Install coverage & plotting tools
        run: |
          python -m pip install --upgrade pip
          pip install coverage matplotlib

      - name: Merge coverage XMLs
        run: |
          # mueve los xmls a la raíz con nombres fijos
          mv cov_reports/coverage-ms_compras.xml coverage-ms_compras.xml
          mv cov_reports/coverage-ms_inventarios.xml coverage-ms_inventarios.xml
          # genera uno unificado incluyendo solo tus carpetas de servicio
          coverage xml \
            --include="services/ms_compras/*,services/ms_inventarios/*" \
            -o merged_coverage.xml

      - name: Generate coverage chart
        run: |
          python services/scripts/generate_coverage_chart.py \
            merged_coverage.xml \
            coverage_chart.png

      - name: Upload coverage chart
        uses: actions/upload-artifact@v4
        with:
          name: coverage-chart
          path: coverage_chart.png