name: CI Coverage

on:
  pull_request:
    paths:
      - "services/ms_compras/**"
      - "services/ms_inventarios/**"
      - ".github/workflows/ci-coverage.yml"
  push:
    branches: [master]

jobs:
  ms_compras:
    name: Tests and coverage for ms_compras
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install -r services/ms_compras/requirements.txt
          pip install pytest pytest-cov
      - name: Run tests
        run: |
          cd services/ms_compras
          pytest -q tests --cov=. --cov-report=xml:coverage.xml --cov-report=html:htmlcov
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-ms_compras
          path: services/ms_compras/coverage.xml

  ms_inventarios:
    name: Tests and coverage for ms_inventarios
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install -r services/ms_inventarios/requirements.txt
          pip install pytest pytest-cov
      - name: Run tests
        run: |
          cd services/ms_inventarios
          pytest -q tests --cov=. --cov-report=xml:coverage.xml --cov-report=html:htmlcov
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-ms_inventarios
          path: services/ms_inventarios/coverage.xml

  aggregate:
    name: Aggregate coverage
    needs: [ms_compras, ms_inventarios]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Combine coverage reports
        run: |
          pip install coverage
          coverage combine artifacts/coverage-ms_compras/coverage.xml artifacts/coverage-ms_inventarios/coverage.xml
          coverage html -d htmlcov
      - uses: actions/upload-artifact@v4
        with:
          name: final-html-coverage
          path: htmlcov