name: E2E Integration Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  e2e:
    name: Run E2E Integration Suite
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies from requirements.txt
        working-directory: services/tests/integration
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run E2E integration test
        working-directory: services/tests/integration
        run: pytest test_e2e.py