name: unit-recomendations-command

on:
  pull_request:
    paths:
      - "services/recomendations_command/**"
      - ".github/workflows/unit-recomendations-command.yml"
  push:
    branches: [master]
    paths:
      - "services/recomendations_command/**"

jobs:
  unit:
    runs-on: ubuntu-latest
    env:
      VIDEO_BUCKET: "videos_tiendas"
      GCP_PROJECT: "misw-4301-native-cloud-433702"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install deps
        run: |
          pip install -r services/recomendations_command/requirements.txt
          pip install pytest pytest-cov

      - name: Run tests + coverage
        working-directory: services/recomendations_command
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest -q tests \
            --cov=src \
            --cov-report=xml \
            --cov-report=html:cov_html

      - uses: actions/upload-artifact@v4
        with:
          name: coverage-recomendations_command
          path: services/recomendations_command/cov_html
