name: unit-recomendations-command

on:
  pull_request:
    paths:
      - "services/recomendations_command/**"
      - ".github/workflows/unit-recomendations-command.yml"
  push:
    branches: [master]
    paths:
      - "services/recomendations_command/**"

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install deps
        run: |
          pip install -r services/recomendations_command/requirements.txt
          pip install pytest pytest-cov

      - name: Run tests + coverage
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/services/recomendations_command/src
          pytest -q services/recomendations_command/tests \
            --cov=services/recomendations_command \
            --cov-report=xml \
            --cov-report=html:cov_html

      - uses: actions/upload-artifact@v4
        with:
          name: coverage-recomendations_command
          path: cov_html