name: unit-ms_compras

on:
  pull_request:
    paths:
      - "services/ms_compras/**"
      - ".github/workflows/unit-ms_compras.yml"
  push:
    branches: [master]
    paths:
      - "services/ms_compras/**"

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r services/ms_compras/requirements.txt
          pip install pytest pytest-cov

      - name: Run tests + coverage
        run: |
          pytest -q services/ms_compras/tests \
            --cov=services/ms_compras \
            --cov-report=xml:coverage.xml \
            --cov-report=html:cov_html

      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-ms_compras
          path: cov_html