name: unit-pedidos

on:
  pull_request:
    paths:
      - "services/pedidos/**"
      - ".github/workflows/unit-pedidos.yml"
  push:
    branches: [master]
    paths:
      - "services/pedidos/**"

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.12"}

      - name: Install deps
        run: |
          pip install -r services/pedidos/requirements.txt
          pip install pytest pytest-cov

      - name: Run tests + coverage
        run: |
          pytest -q services/pedidos/tests \
            --cov=services/pedidos \
            --cov-report=xml \
            --cov-report=html:cov_html

      - uses: actions/upload-artifact@v4
        with:
          name: coverage-pedidos
          path: cov_html