name: unit-ms_compras

on:
  pull_request:
    paths:
      - "services/ms_compras/**"
  push:
    branches: [master]
    paths:
      - "services/ms_compras/**"

jobs:
  unit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/ms_compras

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests & produce XML coverage report
        run: |
          pytest \
            --cov=services/ms_compras \
            --cov-report=term \
            --cov-report=xml:coverage.xml \
            -q tests/

      - name: Upload coverage.xml
        uses: actions/upload-artifact@v4
        with:
          name: cov-ms_compras
          path: services/ms_compras/coverage.xml