name: unit-recomendations-query

on:
  pull_request:
    paths:
      - "services/recomendations-query/**"
      - ".github/workflows/unit-recomendations-query.yml"
  push:
    branches: [master]
    paths:
      - "services/recomendations-query/**"

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.9"}

      - name: Install deps
        run: |
          pip install -r services/recomendations-query/requirements.txt
          pip install pytest pytest-cov

      - name: Run tests + coverage
        run: |
          pytest -q services/recomendations-query/tests \
            --cov=services/recomendations-query \
            --cov-report=xml \
            --cov-report=html:cov_html

      - uses: actions/upload-artifact@v4
        with:
          name: coverage-recomendations-query
          path: cov_html