name: unit-ms_compras

on:
  pull_request:
    paths: ["services/ms_compras/**"]
  push:
    branches: [master]
    paths: ["services/ms_compras/**"]

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          pip install -r services/ms_compras/requirements.txt
          pip install pytest pytest-cov matplotlib lxml

      - name: Run tests with coverage
        working-directory: services/ms_compras
        run: |
          pytest -q tests \
            --cov=services.ms_compras \
            --cov-report=xml \
            --cov-report=html:cov_html

      # ───── PASO NUEVO ─────
      - name: Generate coverage chart
        working-directory: services/ms_compras
        run: |
          python scripts/generate_coverage_chart.py

      # ───── Artefactos ─────
      - name: Upload HTML coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html-ms_compras
          path: services/ms_compras/cov_html

      - name: Upload coverage chart
        uses: actions/upload-artifact@v4
        with:
          name: coverage-chart-ms_compras
          path: services/ms_compras/coverage_chart.png