name: unit-ms_compras

on:
  pull_request:
    paths:
      - 'services/ms_compras/**'
  push:
    branches: [master]
    paths:
      - 'services/ms_compras/**'

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r services/ms_compras/requirements.txt
          pip install pytest pytest-cov matplotlib lxml

      - name: Run tests with coverage
        run: |
          pytest \
            --cov=services/ms_compras \
            --cov-report=xml:coverage.xml \
            --cov-report=html:cov_html \
            -q services/ms_compras/tests

      - name: Verify coverage.xml exists
        run: |
          test -f coverage.xml || (echo "❌ coverage.xml not found" && exit 1)

      - name: Generate coverage chart
        run: |
          python services/scripts/generate_coverage_chart.py \
            coverage.xml \
            coverage_chart.png

      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html-ms_compras
          path: cov_html

      - name: Upload coverage chart
        uses: actions/upload-artifact@v4
        with:
          name: coverage-chart-ms_compras
          path: coverage_chart.png