# .github/workflows/unit-ms_compras.yaml
name: unit-ms_compras

on:
  pull_request:
    paths:
      - "services/ms_compras/**"
      - ".github/workflows/unit-ms_compras.yaml"
  push:
    branches: [master]
    paths:
      - "services/ms_compras/**"
      - ".github/workflows/unit-ms_compras.yaml"

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r services/ms_compras/requirements.txt
          pip install pytest pytest-cov matplotlib lxml

      - name: Run tests & generate coverage files
        working-directory: services/ms_compras
        run: |
          # Ejecuta los tests, fuerza XML y HTML en el cwd (services/ms_compras)
          pytest -q tests \
            --cov=. \
            --cov-report=xml:coverage.xml \
            --cov-report=html:htmlcov

          # Para debug: listar archivos y confirmar que coverage.xml existe
          ls -la .

      - name: Generate coverage chart
        # Este paso se ejecuta desde la raíz del repo
        run: |
          python services/scripts/generate_coverage_chart.py \
            services/ms_compras/coverage.xml \
            services/ms_compras

      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html-ms_compras
          path: services/ms_compras/htmlcov

      - name: Upload coverage chart PNG
        uses: actions/upload-artifact@v4
        with:
          name: coverage-chart-ms_compras
          path: services/ms_compras/coverage_chart.png