name: unit-ms_compras

on:
  pull_request:
    paths:
      - "services/ms_compras/**"
  push:
    branches: [master]
    paths:
      - "services/ms_compras/**"

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          pip install -r services/ms_compras/requirements.txt
          pip install pytest pytest-cov matplotlib lxml

      - name: Run tests & generate coverage reports
        run: |
          pytest services/ms_compras/tests \
            --cov=services/ms_compras \
            --cov-report=xml:coverage.xml \
            --cov-report=html:htmlcov

      - name: Generate coverage chart PNG
        run: |
          # Aquí usamos la ruta correcta al script en scripts/
          python scripts/generate_coverage_chart.py \
            coverage.xml \
            coverage_chart.png

      - name: Embed coverage chart in summary
        run: |
          echo "## 📊 Test Coverage" >> $GITHUB_STEP_SUMMARY
          echo "![Coverage](data:image/png;base64,$(base64 -w0 coverage_chart.png))" >> $GITHUB_STEP_SUMMARY

      - name: Upload HTML report + chart as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-ms_compras
          path: |
            htmlcov
            coverage_chart.png