# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Ventas CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'services/ventas/**'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    environment: VENTAS_CI
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r services/ventas/requirements.txt
    - name: Get Keys File
      run: echo ${{ secrets._FIREBASE_ADMIN_KEYS }} | base64 -d > keys.json
    - name: Start PostgreSQL
      run: |
        docker run --name postgres -e POSTGRES_USER=${{vars.DATABASE_USER}} -e POSTGRES_PASSWORD=${{vars.DATABASE_PASSWORD}} -e POSTGRES_DB=${{vars.DATABASE_NAME}}  -p ${{vars.DATABASE_PORT}}:5432 -d postgres 
    - name: Test with pytest
      env:
        FLASK_DEBUG: ${{ vars.FLASK_DEBUG }}
        DATABASE_USER: ${{ vars.DATABASE_USER }}
        DATABASE_PASSWORD: ${{ vars.DATABASE_PASSWORD }}
        DATABASE_NAME: ${{ vars.DATABASE_NAME }}
        DATABASE_PORT: ${{ vars.DATABASE_PORT }}
        DATABASE_URL: ${{ vars.DATABASE_URL }}
      run: |
        coverage run -m pytest services/ventas
    - name: Coverage Report
      run: |
        coverage report
      
